### ISSUE TITLE
Request: solar power readout

### ISSUE THREAD

**Issue by Ponseldirk** [Baumus/com.baumus.rctpowerstorage#1]
Hi Baumus,

thanks so much for bringing RCT into Homey integration!
Despite the fact I have no idea how comlicated it is, may I ask you for two additional functionalities? 
One of a key missing feature would be to read out the actual solar power coming in. Second, it would be great to implement "AND" rules in order to easily connect wihtin a flow e.g. solar power >3000W and battery >80% then...turn on heat pump  

Again thank you so much for programming the app!
Best, Dirk

**Comment by Baumus** [comment]
Hi Dirk,
thanks for your suggestions. Please feel free to install the test version (https://homey.app/de-de/app/com.baumus.rctpowerstorage/RCT-Power-Storage-DC/test/). The next release will have the two conditional flow cards included you asked for. Best regards, Robin

**Comment by Ponseldirk** [comment]
Hi Robin, unbelievable, Thanks so much! I will test asap.Best, Dirk Gesendet mit der GMX Mail AppAm 14.02.24 um 22:19 schrieb Baumus
                
            
            
                
                    Von: "Baumus" ***@***.***>Datum: 14. Februar 2024An: "Baumus/com.baumus.rctpowerstorage" ***@***.***>Cc: "Author" ***@***.***>,"Ponseldirk" ***@***.***>Betreff: Re: [Baumus/com.baumus.rctpowerstorage] Request: solar power readout (Issue #1)
                
                
Hi Dirk,
thanks for your suggestions. Please feel free to install the test version (https://homey.app/de-de/app/com.baumus.rctpowerstorage/RCT-Power-Storage-DC/test/). The next release will have the two conditional flow cards included you asked for. Best regards, Robin
