### ISSUE TITLE
Info request: Default port of RCT Power Storage DC?

### ISSUE THREAD

**Issue by j0er9** [Baumus/com.baumus.rctpowerstorage#2]
Hi Robin,

I like to connect my Homey to my RCT Power Storage inverter. When adding a new device to Homey beside the IP also a port is required as parameter. 
Can you share the default port or/and the setting of the inverter where to find the port?

Thanks a lot,
j0er9

**Comment by Baumus** [comment]
The default port of the inverter should be 8899. You can read / change the settings in network setting > wifi / ethernet setup in your rct app. Hope this helps ;)

**Comment by j0er9** [comment]
Thanks a lot. And cool to have that default port now in the setup dialog prefilled. 👍
Unfortunately that did not solve my connection problem. 8899 ist also not working for me. I am still not able to connect. Maybe I need to enable something on the inverter itself? 

Update: Connection is working now. No Idea what has changed. Nethertheless thanks for the cool plugin
